FROM public.ecr.aws/lambda/python:3.12

WORKDIR ${LAMBDA_TASK_ROOT}
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY pipeline ./pipeline
COPY api ./api
CMD ["pipeline.run_pipeline.lambda_handler"]
