from __future__ import annotations

from typing import Any, Protocol


class AIClient(Protocol):
    def score_sentiment_batch(self, *, ticker: str, source_name: str, texts: list[str]) -> dict[str, Any]: ...
    def generate_analysis(self, *, ticker: str, price_data: dict[str, Any], technicals: dict[str, Any], sentiment: dict[str, Any], macro: dict[str, Any]) -> dict[str, Any]: ...
    def generate_earnings_story(self, *, ticker: str, run_data: dict[str, Any]) -> dict[str, Any]: ...
    def generate_news_draft(self, *, ticker: str, run_data: dict[str, Any]) -> dict[str, Any]: ...
