from __future__ import annotations

from typing import Any, Protocol


class StorageProvider(Protocol):
    def init(self) -> None: ...
    def save_run(self, result: dict[str, Any]) -> None: ...
    def get_latest_run(self, ticker: str) -> dict[str, Any] | None: ...
    def get_all_latest(self) -> list[dict[str, Any]]: ...
    def get_history(self, ticker: str, days: int = 30) -> list[dict[str, Any]]: ...
    def load_watchlist(self) -> list[str]: ...
    def save_watchlist(self, tickers: list[str]) -> None: ...
    def create_run_status(self, run_id: str, status: str, source: str, tickers: list[str] | None = None) -> None: ...
    def update_run_status(self, run_id: str, status: str, **fields: Any) -> None: ...
    def get_run_status(self, run_id: str) -> dict[str, Any] | None: ...
